DROP TABLE IF EXISTS tor_exit;

CREATE TABLE tor_exit (
  nm  TEXT NOT NULL,
  ip  TEXT NOT NULL,
  op  INTEGER NOT NULL,
  dp  INTEGER NOT NULL,
  dt  NUMERIC NOT NULL,
  tm  NUMERIC NOT NULL,
  fp1 TEXT NOT NULL,
  fp2 TEXT NOT NULL,
  st  TEXT NOT NULL,
  er  INTEGER DEFAULT 0,
  PRIMARY KEY (ip),
  UNIQUE (ip)
);
