#!/bin/bash

echo "deb http://apt.opscode.com/ precise-0.10 main" | \
sudo tee /etc/apt/sources.list.d/opscode.list

sudo mkdir -p /etc/apt/trusted.gpg.d
gpg --keyserver keys.gnupg.net --recv-keys 83EF826A
gpg --export packages@opscode.com | \
sudo tee /etc/apt/trusted.gpg.d/opscode-keyring.gpg

sudo apt-get update
sudo apt-get install opscode-keyring
sudo apt-get upgrade
sudo apt-get install chef chef-server

mkdir -p ~/.chef
sudo cp /etc/chef/validation.pem /etc/chef/webui.pem ~/.chef
sudo chown -R $USER ~/.chef
